/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopoly1;

/**
 *
 * @author huyph
 */
public class board extends javax.swing.JFrame {

    /**
     * Creates new form board
     */
    public board() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        parkingLabel = new javax.swing.JLabel();
        NEW_YORK = new javax.swing.JLabel();
        electric = new javax.swing.JLabel();
        MUMBAI = new javax.swing.JLabel();
        DUBAI = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TORONTO = new javax.swing.JLabel();
        chest3 = new javax.swing.JLabel();
        DUBLIN = new javax.swing.JLabel();
        COPENHAGEN = new javax.swing.JLabel();
        gotojailLabel = new javax.swing.JLabel();
        ROME = new javax.swing.JLabel();
        HA_NOI = new javax.swing.JLabel();
        HCM = new javax.swing.JLabel();
        chance1 = new javax.swing.JLabel();
        chance3 = new javax.swing.JLabel();
        MADRID = new javax.swing.JLabel();
        luxury = new javax.swing.JLabel();
        PARIS = new javax.swing.JLabel();
        BANGKOK = new javax.swing.JLabel();
        water = new javax.swing.JLabel();
        chest2 = new javax.swing.JLabel();
        LONDON = new javax.swing.JLabel();
        SINGAPORE = new javax.swing.JLabel();
        BERLIN = new javax.swing.JLabel();
        visitlLabel = new javax.swing.JLabel();
        goLabel = new javax.swing.JLabel();
        BEIJING = new javax.swing.JLabel();
        SEOUL = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        TOKYO = new javax.swing.JLabel();
        chance2 = new javax.swing.JLabel();
        income = new javax.swing.JLabel();
        LAGOS = new javax.swing.JLabel();
        chest1 = new javax.swing.JLabel();
        CAIRO = new javax.swing.JLabel();
        chanceButton = new javax.swing.JButton();
        chestButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        endButton = new javax.swing.JButton();
        sellButton = new javax.swing.JButton();
        buildButton = new javax.swing.JButton();
        player1 = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        intro = new javax.swing.JLabel();
        diceLabel = new javax.swing.JLabel();
        dice1 = new javax.swing.JLabel();
        dice2 = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MONOPOLY");
        getContentPane().setLayout(null);

        parkingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/free-parking.jpg"))); // NOI18N
        parkingLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(parkingLabel);
        parkingLabel.setBounds(2, 13, 100, 90);

        NEW_YORK.setText("   NEW YORK");
        NEW_YORK.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 4, true));
        getContentPane().add(NEW_YORK);
        NEW_YORK.setBounds(109, 13, 90, 90);

        electric.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/electric.jpg"))); // NOI18N
        electric.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(electric);
        electric.setBounds(206, 13, 90, 90);

        MUMBAI.setText("    MUMBAI");
        MUMBAI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 4, true));
        getContentPane().add(MUMBAI);
        MUMBAI.setBounds(303, 13, 90, 90);

        DUBAI.setText("     DUBAI");
        DUBAI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 4, true));
        getContentPane().add(DUBAI);
        DUBAI.setBounds(400, 13, 90, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(497, 13, 90, 90);

        TORONTO.setText("    TORONTO");
        TORONTO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 4, true));
        getContentPane().add(TORONTO);
        TORONTO.setBounds(594, 13, 90, 90);

        chest3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/monopoly-community-chest-703695.gif"))); // NOI18N
        chest3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(chest3);
        chest3.setBounds(691, 13, 90, 90);

        DUBLIN.setText("    DUBLIN");
        DUBLIN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 4, true));
        getContentPane().add(DUBLIN);
        DUBLIN.setBounds(788, 13, 90, 90);

        COPENHAGEN.setText(" COPENHAGEN");
        COPENHAGEN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 4, true));
        getContentPane().add(COPENHAGEN);
        COPENHAGEN.setBounds(885, 13, 90, 90);

        gotojailLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/jail-debts.jpg"))); // NOI18N
        gotojailLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gotojailLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(gotojailLabel);
        gotojailLabel.setBounds(980, 10, 100, 94);

        ROME.setBackground(new java.awt.Color(0, 153, 51));
        ROME.setText("   ROME");
        ROME.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 4, true));
        getContentPane().add(ROME);
        ROME.setBounds(982, 110, 90, 90);

        HA_NOI.setText("    HA NOI");
        HA_NOI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 4, true));
        getContentPane().add(HA_NOI);
        HA_NOI.setBounds(12, 110, 90, 90);

        HCM.setText("  HCM CITY");
        HCM.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 4, true));
        getContentPane().add(HCM);
        HCM.setBounds(12, 207, 90, 90);

        chance1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N
        chance1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(chance1);
        chance1.setBounds(982, 207, 90, 90);

        chance3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N
        chance3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(chance3);
        chance3.setBounds(12, 304, 90, 90);

        MADRID.setText("   MADRID");
        MADRID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 4, true));
        getContentPane().add(MADRID);
        MADRID.setBounds(982, 304, 90, 90);

        luxury.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/luxury.jpg"))); // NOI18N
        luxury.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(luxury);
        luxury.setBounds(12, 401, 90, 90);

        PARIS.setText("   PARIS");
        PARIS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 4, true));
        getContentPane().add(PARIS);
        PARIS.setBounds(982, 401, 90, 90);

        BANGKOK.setText("    BANGKOK");
        BANGKOK.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 4, true));
        getContentPane().add(BANGKOK);
        BANGKOK.setBounds(12, 498, 90, 90);

        water.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/water.jpg"))); // NOI18N
        water.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(water);
        water.setBounds(982, 498, 90, 90);

        chest2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/monopoly-community-chest-703695.gif"))); // NOI18N
        chest2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(chest2);
        chest2.setBounds(12, 595, 90, 90);

        LONDON.setText("    LONDON");
        LONDON.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 4, true));
        getContentPane().add(LONDON);
        LONDON.setBounds(982, 595, 90, 90);

        SINGAPORE.setText("  SINGAPORE");
        SINGAPORE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 4, true));
        getContentPane().add(SINGAPORE);
        SINGAPORE.setBounds(12, 692, 90, 90);

        BERLIN.setText("    BERLIN");
        BERLIN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 4, true));
        getContentPane().add(BERLIN);
        BERLIN.setBounds(982, 692, 90, 90);

        visitlLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/monopoly-jail.jpg"))); // NOI18N
        visitlLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(visitlLabel);
        visitlLabel.setBounds(2, 789, 100, 90);

        goLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PartyGo.jpg"))); // NOI18N
        goLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(goLabel);
        goLabel.setBounds(980, 790, 100, 94);

        BEIJING.setText("    BEIJING");
        BEIJING.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        getContentPane().add(BEIJING);
        BEIJING.setBounds(109, 789, 90, 90);

        SEOUL.setText("    SEOUL");
        SEOUL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        getContentPane().add(SEOUL);
        SEOUL.setBounds(206, 789, 90, 90);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/monopoly-community-chest-703695.gif"))); // NOI18N
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(jLabel30);
        jLabel30.setBounds(303, 789, 90, 90);

        TOKYO.setText("    TOKYO");
        TOKYO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        getContentPane().add(TOKYO);
        TOKYO.setBounds(400, 789, 90, 90);

        chance2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N
        chance2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(chance2);
        chance2.setBounds(497, 789, 90, 90);

        income.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Monopoly_income_tax_space_US_pre-2008.jpg"))); // NOI18N
        income.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(income);
        income.setBounds(594, 789, 90, 90);

        LAGOS.setText("    LAGOS");
        LAGOS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 4, true));
        getContentPane().add(LAGOS);
        LAGOS.setBounds(691, 789, 90, 90);

        chest1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/monopoly-community-chest-703695.gif"))); // NOI18N
        chest1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(chest1);
        chest1.setBounds(788, 789, 90, 90);

        CAIRO.setText("     CAIRO");
        CAIRO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 4, true));
        getContentPane().add(CAIRO);
        CAIRO.setBounds(885, 789, 90, 90);

        chanceButton.setBackground(new java.awt.Color(102, 102, 102));
        chanceButton.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        chanceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chance.jpg"))); // NOI18N
        chanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chanceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(chanceButton);
        chanceButton.setBounds(150, 240, 200, 90);

        chestButton.setBackground(new java.awt.Color(102, 102, 102));
        chestButton.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        chestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chestjpg.jpg"))); // NOI18N
        getContentPane().add(chestButton);
        chestButton.setBounds(720, 230, 200, 90);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setText("Roll Dice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 520, 110, 30);

        endButton.setBackground(new java.awt.Color(102, 102, 102));
        endButton.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        endButton.setText("End Turn");
        getContentPane().add(endButton);
        endButton.setBounds(220, 590, 110, 29);

        sellButton.setBackground(new java.awt.Color(102, 102, 102));
        sellButton.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        sellButton.setText("Sell");
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sellButton);
        sellButton.setBounds(790, 540, 90, 29);

        buildButton.setBackground(new java.awt.Color(102, 102, 102));
        buildButton.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        buildButton.setText("Build");
        buildButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buildButton);
        buildButton.setBounds(790, 590, 90, 29);

        player1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        player1.setText("Player 1:");
        getContentPane().add(player1);
        player1.setBounds(1130, 310, 120, 16);

        player2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        player2.setText("Player 2:");
        getContentPane().add(player2);
        player2.setBounds(1330, 310, 80, 20);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Roll the dice.\n2. You must have a monopoly\nin order to build.\n3. To open Chance/ Community,\nclick the Chance/ Community\nbutton.\n4. To end your turn, click End \nturn button.\n");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1210, 110, 210, 170);

        intro.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        intro.setForeground(new java.awt.Color(255, 51, 0));
        intro.setText("INTRODUCTIONS:");
        getContentPane().add(intro);
        intro.setBounds(1250, 80, 150, 16);
        getContentPane().add(diceLabel);
        diceLabel.setBounds(520, 220, 0, 40);

        dice1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Dice/diceSix.jpeg"))); // NOI18N
        dice1.setText("jLabel11");
        getContentPane().add(dice1);
        dice1.setBounds(200, 420, 50, 50);

        dice2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Dice/diceSix.jpeg"))); // NOI18N
        dice2.setText("jLabel1");
        getContentPane().add(dice2);
        dice2.setBounds(300, 420, 50, 50);

        buyButton.setBackground(new java.awt.Color(102, 102, 102));
        buyButton.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        buyButton.setText("Buy");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buyButton);
        buyButton.setBounds(790, 480, 90, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/424113.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 110, 860, 670);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Cash: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1100, 350, 50, 17);

        jTextField1.setText("$10000");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(1150, 340, 69, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Cash:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1280, 350, 50, 17);

        jTextField2.setText("$10000");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(1340, 340, 90, 30);

        setSize(new java.awt.Dimension(1552, 951));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellButtonActionPerformed

    private void buildButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buildButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chanceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chanceButtonActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        
    }//GEN-LAST:event_buyButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new board().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BANGKOK;
    private javax.swing.JLabel BEIJING;
    private javax.swing.JLabel BERLIN;
    private javax.swing.JLabel CAIRO;
    private javax.swing.JLabel COPENHAGEN;
    private javax.swing.JLabel DUBAI;
    private javax.swing.JLabel DUBLIN;
    private javax.swing.JLabel HA_NOI;
    private javax.swing.JLabel HCM;
    private javax.swing.JLabel LAGOS;
    private javax.swing.JLabel LONDON;
    private javax.swing.JLabel MADRID;
    private javax.swing.JLabel MUMBAI;
    private javax.swing.JLabel NEW_YORK;
    private javax.swing.JLabel PARIS;
    private javax.swing.JLabel ROME;
    private javax.swing.JLabel SEOUL;
    private javax.swing.JLabel SINGAPORE;
    private javax.swing.JLabel TOKYO;
    private javax.swing.JLabel TORONTO;
    private javax.swing.JButton buildButton;
    private javax.swing.JButton buyButton;
    private javax.swing.JLabel chance1;
    private javax.swing.JLabel chance2;
    private javax.swing.JLabel chance3;
    private javax.swing.JButton chanceButton;
    private javax.swing.JLabel chest1;
    private javax.swing.JLabel chest2;
    private javax.swing.JLabel chest3;
    private javax.swing.JButton chestButton;
    private javax.swing.JLabel dice1;
    private javax.swing.JLabel dice2;
    private javax.swing.JLabel diceLabel;
    private javax.swing.JLabel electric;
    private javax.swing.JButton endButton;
    private javax.swing.JLabel goLabel;
    private javax.swing.JLabel gotojailLabel;
    private javax.swing.JLabel income;
    private javax.swing.JLabel intro;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel luxury;
    private javax.swing.JLabel parkingLabel;
    private javax.swing.JLabel player1;
    private javax.swing.JLabel player2;
    private javax.swing.JButton sellButton;
    private javax.swing.JLabel visitlLabel;
    private javax.swing.JLabel water;
    // End of variables declaration//GEN-END:variables
}
